//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication3.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=123.231.45.252;Initial Catalog=CallCenterCityCab;User ID=sa;Password=" +
            "sirasa588")]
        public string CallCenterCityCabConnectionString {
            get {
                return ((string)(this["CallCenterCityCabConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=123.231.45.252;User Id=CabPayment;password=cab588588;database=budget;Persi" +
            "st Security Info=True")]
        public string budgetConnectionString1 {
            get {
                return ((string)(this["budgetConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;database=CabPayment;Pe" +
            "rsist Security Info=True")]
        public string CabPaymentConnectionString1 {
            get {
                return ((string)(this["CabPaymentConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Dsn=CabPayment;database=CabPayment;option=0;pwd=lobos681;port=0;server=202.124.16" +
            "1.219;uid=CabPayment")]
        public string CabPaymentConnectionString {
            get {
                return ((string)(this["CabPaymentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;Persist Security Info=" +
            "True;database=Amila")]
        public string AmilaConnectionString {
            get {
                return ((string)(this["AmilaConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;Persist Security Info=" +
            "True;database=CabPayment")]
        public string CabPaymentConnectionString2 {
            get {
                return ((string)(this["CabPaymentConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;database=Payment;Persi" +
            "st Security Info=True")]
        public string PaymentConnectionString {
            get {
                return ((string)(this["PaymentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;database=Calling_numbe" +
            "r;Persist Security Info=True")]
        public string Calling_numberConnectionString1 {
            get {
                return ((string)(this["Calling_numberConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;database=bookings;Pers" +
            "ist Security Info=True")]
        public string bookingsConnectionString {
            get {
                return ((string)(this["bookingsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;database=budget;Persis" +
            "t Security Info=True")]
        public string budgetConnectionString {
            get {
                return ((string)(this["budgetConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=202.124.161.219;User Id=usr_local;password=lobos681;Persist Security Info=" +
            "True;database=accounts_reports")]
        public string accounts_reportsConnectionString {
            get {
                return ((string)(this["accounts_reportsConnectionString"]));
            }
        }
    }
}
